In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Projects /CREDIT RISK MODELLING/loan_data_2007_2014.csv")

/tmp/ipython-input-4-2936393266.py:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/drive/MyDrive/Projects /CREDIT RISK MODELLING/loan_data_2007_2014.csv")

In [ ]:
pd.set_option('display.max_columns',None) #None basically tells us dont limit the number of columns.Show all
pd.set_option('display.max_rows',None)

### INFORMATION ABOUT THE FEATURES-
* id-an unique ID assigned for the loan listing

* member id- an unique ID assigned for the borrower member

* loan_amnt-the amount that was applied for.

* funded_amnt-the amount that was lended.

* funded_amnt_inv-the amount that was invested exc lending club.

* term - duration of loan 36/60 months

* int_rate - interest rate

* installment-the monthly payment owed by borrower

* grade- loan assigned loan grade
(from A to G)

* subgrade - loan assigned subgrade(A1,A2,A3,A4,A5 and so on till G)

* emp_title - job title provided by the borrower

* home_ownership- home status of borrower

* annual_inc - annual income of borrower

* verification_status - if borrowers income was verified or not

* issue_d - issue date of loan

* **loan_status - the current status of loan**


  *   Fully Paid - completely paided off
*   Charged Off - DEFAULTED
*   Current - The loan is active
*   Late - 31 to 120 days late
*   Late - 16 to 30 days late
*   In grace period - just missed the due date and is late by few days
*   Does not meet the credit policy. Status:Fully Paid - Fully Paid
*   Does not meet the credit policy. Status:Charged Off - Charged Off
*   Defaulted - defaulted

* purpose - purpose stated for the loan

* title - provided by the borrower

* zip_code - geographical use

* addr_state - the state of borrower

*  **dti - the debt to income ratio (HIGHER MEANS MORE CHANCES OF BEING A DEFAULTER)**

* delinq_2yrs - how many times the borrower has missed a 30+days due for the loan in last 2 years.

* earliest_cr_line - The month the borrower’s earliest reported credit line was opened.
    *   Helps assess the length of the borrower’s credit history.

    *   A longer credit history is generally a sign of lower credit risk (more experience managing debt).

* inq_last_6mths - Number of credit inquiries in the last 6 months (prior to loan application).This value indicates recent borrowing activity or attempts to get new credit.

* mths_since_last_delinq - The number of months since the borrower's last delinquency

* mths_since_last_record- The number of months since the borrower’s last public record.
A public record on a credit report usually refers to:

  *  Bankruptcy

  *  Tax lien

  *  Judgment

  These are serious negative marks and indicate severe credit events.

* open_acc - The number of open credit lines in the borrower's credit file.average value is considered good.

* pub_rec - indicates the number of derogatory public records listed on the borrower’s credit report.Public records are strong indicators of prior financial distress.Even one public record can significantly increase the likelihood of default.

* revol_bal - represents the total outstanding balance on all revolving credit accounts.A high revol_bal means the borrower is carrying large amounts of credit card or line-of-credit debt, which is unsecured and high-interest.

* revol_util - the percentage of available revolving credit (e.g., credit cards, lines of credit) that the borrower is currently using.

  *  revol_util = revol_bal/credit limit * 100

* total_acc	- total credit accounts

* initial_list_status -  indicates the initial status of the loan when it was first listed on the LendingClub platform.

  * w	(Whole)	- The loan was available for a single investor to fund in full. Typically institutional investors.
  * f	(Fractional) -	The loan was listed for multiple retail investors to fund in parts (i.e., "notes").

* out_prncp -  the total unpaid principal amount that is still outstanding on the loan at the time of record.
It does not include any interest — only the remaining principal that the borrower still owes.

* total_pymnt - the cumulative amount of money the borrower has paid to date for the loan — including:
  * Principal
  * Interest
  * Fees
  * Late fees (if any)

  It reflects the actual cash flow received from the borrower over the life of the loan (until the current date or charge-off).

* total_rec_prncp - refers to the total amount of principal (not interest) that has been repaid by the borrower to date.

  It excludes:

  * Interest payments

  * Late fees

  * Service charges

  It tells us how much of the original loan amount the borrower has actually paid back.

* total_rec_int - the total amount of interest that the borrower has paid on the loan up to the current reporting date.

* total_rec_late_fee - the cumulative amount of late fees that the borrower has actually paid on the loan till date.

* recoveries - the amount of money recovered from the borrower after a loan was charged-off (i.e., marked as a loss).
It only applies to defaulted loans and indicates post-default cash recovery.

* collection_recovery_fee - the amount paid by LendingClub (and charged to investors) as a fee for recovering funds from borrowers after a loan was charged-off.It represents the cost of hiring collection agencies, legal services, or internal recovery efforts.

* last_pymnt_d - last payment date(month)

* last_pymnt_amnt	- last payment amount(principal + interest + any fee).

* next_pymnt_d - next payment date

* last_credit_pull_d - The last date LendingClub pulled the borrower’s credit report from a bureau (e.g., TransUnion).

* collections_12_mths_ex_med - The number of collection accounts (excluding medical) opened in the borrower’s credit report in the last 12 months.Reflects recent delinquency behavior, excluding medical collections (which are less predictive of credit risk).

* mths_since_last_major_derog - The number of months since the borrower’s last major derogatory mark, such as:

* policy_code - This code indicates the credit policy version under which the loan was issued.

* application_type - indicates whether the loan application was made by a single borrower or jointly with a co-borrower.

*  acc_now_delinq - The borrower currently has 2 accounts that are delinquent (i.e., past due and unpaid).

* tot_coll_amt - The total amount currently in collections, excluding medical, across all of the borrower’s accounts.Represents unpaid debt sent to collections. A high value implies ongoing credit distress.

* tot_cur_bal - The sum of the current outstanding balances on all open credit lines (e.g., credit cards, mortgages, auto loans).

* total_rev_hi_lim - The sum of all revolving credit limits (mostly credit cards) that the borrower has available, based on their credit report.


* good_loan -
    * 1 represents paid off
    * 0 represents defaulter

In [ ]:
df.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125981 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466264 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(7), object(22)
memory usage: 266.8+ MB

In [ ]:
#dropping this column as it is a constant column
df['application_type'].value_counts()

application_type
INDIVIDUAL    466285
Name: count, dtype: int64

In [ ]:
df['verification_status'].value_counts()

verification_status
Verified           168055
Source Verified    149993
Not Verified       148237
Name: count, dtype: int64

In [ ]:
#dropping this column as it is a constant column
df['policy_code'].value_counts()

policy_code
1    466285
Name: count, dtype: int64

In [ ]:
df.sample()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
341076,341076,22111215,24444178,9000,9000,9000.0,36 months,10.15,291.04,B,B2,Teacher,1 year,RENT,51000.0,Not Verified,Jul-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,122xx,NY,29.88,0.0,Jul-07,3.0,NaN,NaN,11.0,0.0,7084,28.9,18.0,w,5088.45,5088.45,4947.68,4947.68,3911.55,1036.13,0.0,0.0,0.0,Dec-15,291.04,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24500.0,NaN,NaN,NaN

In [ ]:
# dropping columns with 100% missing values
df.columns
df.drop(columns=['annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util','sub_grade', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'inq_fi', 'total_cu_tl',
       'inq_last_12m'],inplace=True)

In [ ]:
#columns - funded_amnt_inv,out_prncp_inv,total_pymnt_inv

In [ ]:
# Highly correlated columns and they convey the same information so dropping funded_amnt_inv
df[['funded_amnt_inv','funded_amnt']].corr()

                 funded_amnt_inv  funded_amnt
funded_amnt_inv         1.000000     0.996125
funded_amnt             0.996125     1.000000

In [ ]:
# Highly correlated columns and they convey the same information so dropping out_prncp_inv
df[['out_prncp_inv','out_prncp']].corr()

               out_prncp_inv  out_prncp
out_prncp_inv       1.000000   0.999998
out_prncp           0.999998   1.000000

In [ ]:
# Highly correlated columns and they convey the same information so dropping total_pymnt_inv
df[['total_pymnt_inv','total_pymnt']].corr()

                 total_pymnt_inv  total_pymnt
total_pymnt_inv         1.000000     0.995862
total_pymnt             0.995862     1.000000

In [ ]:
df['acc_now_delinq'].value_counts()

acc_now_delinq
0.0    464524
1.0      1623
2.0        92
3.0        11
4.0         4
5.0         2
Name: count, dtype: int64

In [ ]:
df.drop(columns=['funded_amnt_inv','out_prncp_inv','total_pymnt_inv','desc'],inplace=True)

In [ ]:
df.drop(columns=['id','member_id','policy_code','application_type'],inplace=True)

In [ ]:
df.drop(columns=['url','pymnt_plan','Unnamed: 0','zip_code'],inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 45 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466285 non-null  int64
 1   funded_amnt                  466285 non-null  int64
 2   term                         466285 non-null  object
 3   int_rate                     466285 non-null  float64
 4   installment                  466285 non-null  float64
 5   grade                        466285 non-null  object
 6   emp_title                    438697 non-null  object
 7   emp_length                   445277 non-null  object
 8   home_ownership               466285 non-null  object
 9   annual_inc                   466281 non-null  float64
 10  verification_status          466285 non-null  object
 11  issue_d                      466285 non-null  object
 12  loan_status                  466285 non-null  object
 13  purpose                      466285 non-null  object
 14  title                        466264 non-null  object
 15  addr_state                   466285 non-null  object
 16  dti                          466285 non-null  float64
 17  delinq_2yrs                  466256 non-null  float64
 18  earliest_cr_line             466256 non-null  object
 19  inq_last_6mths               466256 non-null  float64
 20  mths_since_last_delinq       215934 non-null  float64
 21  mths_since_last_record       62638 non-null   float64
 22  open_acc                     466256 non-null  float64
 23  pub_rec                      466256 non-null  float64
 24  revol_bal                    466285 non-null  int64
 25  revol_util                   465945 non-null  float64
 26  total_acc                    466256 non-null  float64
 27  initial_list_status          466285 non-null  object
 28  out_prncp                    466285 non-null  float64
 29  total_pymnt                  466285 non-null  float64
 30  total_rec_prncp              466285 non-null  float64
 31  total_rec_int                466285 non-null  float64
 32  total_rec_late_fee           466285 non-null  float64
 33  recoveries                   466285 non-null  float64
 34  collection_recovery_fee      466285 non-null  float64
 35  last_pymnt_d                 465909 non-null  object
 36  last_pymnt_amnt              466285 non-null  float64
 37  next_pymnt_d                 239071 non-null  object
 38  last_credit_pull_d           466243 non-null  object
 39  collections_12_mths_ex_med   466140 non-null  float64
 40  mths_since_last_major_derog  98974 non-null   float64
 41  acc_now_delinq               466256 non-null  float64
 42  tot_coll_amt                 396009 non-null  float64
 43  tot_cur_bal                  396009 non-null  float64
 44  total_rev_hi_lim             396009 non-null  float64
dtypes: float64(26), int64(3), object(16)
memory usage: 160.1+ MB

In [ ]:
df.sample()

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim
366091,21300,21300,60 months,25.83,635.6,G,Iron worker,< 1 year,RENT,88000.0,Source Verified,Jun-14,Current,debt_consolidation,Debt consolidation,MN,16.43,0.0,Jun-98,0.0,NaN,86.0,10.0,1.0,12548,67.8,15.0,f,17455.87,11440.8,3844.13,7596.67,0.0,0.0,0.0,Dec-15,635.6,Feb-16,Jan-16,0.0,NaN,0.0,0.0,44596.0,18500.0

In [ ]:
# might change or remove either of the column.Both of them are very similar
df[['purpose','title']].sample(100)

                   purpose                                   title
6579                 other                                   Bills
163424         credit_card                           Straighten Up
144522         credit_card                      credit card payoff
250014         credit_card                 Credit card refinancing
277208  debt_consolidation                      Debt consolidation
296307  debt_consolidation                      Debt consolidation
294166  debt_consolidation                      Debt consolidation
28739   debt_consolidation  Debt Consolidation (Medical/Home Imp.)
246318  debt_consolidation                      Debt consolidation
94266             vacation                                vacation
270474         credit_card                 Credit card refinancing
196558  debt_consolidation                        Credit Card Loan
89878   debt_consolidation                      Debt Consolidation
134432               other                             credit card
35128                  car                   Refinancing auto loan
33742          credit_card                             Credit Card
313936  debt_consolidation                      Debt consolidation
321306  debt_consolidation                      Debt consolidation
270160               other                                   Other
406220  debt_consolidation                      Debt consolidation
309038         credit_card                 Credit card refinancing
445954         credit_card                 Credit card refinancing
299168  debt_consolidation                      Debt consolidation
260779         credit_card                 Credit card refinancing
264751  debt_consolidation                      Debt consolidation
75315   debt_consolidation                      Debt consolidation
398896    home_improvement                        Home improvement
278851  debt_consolidation                      Debt consolidation
15898     home_improvement                           Swimming Pool
160315      major_purchase                                personal
76313          credit_card                                  Payoff
228313  debt_consolidation                                   debt
60771   debt_consolidation                          Debt Free Plan
407145    home_improvement                        Home improvement
191707         credit_card                             CARD PAYOFF
402855         credit_card                 Credit card refinancing
319245  debt_consolidation                      Debt consolidation
223879         credit_card                        Citi Card Payoff
33508   debt_consolidation            Newlywed Debt Consolidation!
449098  debt_consolidation                      Debt consolidation
221277                 car                                   civic
302819  debt_consolidation                      Debt consolidation
5709      home_improvement                      Remodeled Basement
253380  debt_consolidation                      Debt consolidation
369147  debt_consolidation                      Debt consolidation
271720  debt_consolidation                      Debt consolidation
411354  debt_consolidation                      Debt consolidation
342998         credit_card                 Credit card refinancing
16038                  car                                Car loan
308950         credit_card                 Credit card refinancing
342211  debt_consolidation                      Debt consolidation
23452       small_business                    Portfolio purchase 1
167446  debt_consolidation                         CC Payoff Loan
60733   debt_consolidation                                business
5778    debt_consolidation                             School Debt
54738   debt_consolidation                            payoff cards
99961   debt_consolidation                 Auto Debt Consolidation
303442  debt_consolidation                      Debt consolidation
294182  debt_consolidation                      Debt consolidation
347470  debt_consolidation                      Debt consolidation
453696                 car                           Car financing
452386         credit_card                 Credit card refinancing
448319  debt_consolidation                      Debt consolidation
153402  debt_consolidation                           Personal Loan
206585  debt_consolidation                             consolidate
53628     home_improvement                                bussines
305266    home_improvement                        Home improvement
169188         credit_card                 Credit card refinancing
186906         credit_card                 Credit card refinancing
224927      major_purchase                          Major Purchase
270909  debt_consolidation                      Debt consolidation
290673         credit_card                 Credit card refinancing
39301                other                                personal
409728  debt_consolidation                      Debt consolidation
37883   debt_consolidation                                Personal
331278               other                                   Other
26921                house                                new home
25092     home_improvement                             House Rehab
309153  debt_consolidation                      Debt consolidation
106157  debt_consolidation                      Consolidation Plan
243006  debt_consolidation                      Debt consolidation
140395         credit_card                        Debt Elimination
318443         credit_card                 Credit card refinancing
289373  debt_consolidation                      Debt consolidation
58091          credit_card                    Credit Card Closeout
207044  debt_consolidation                      Debt consolidation
440805  debt_consolidation                      Debt consolidation
103775  debt_consolidation    makes good sense and build credit to
84556     home_improvement                        Home improvement
71558          credit_card                           Consolidation
329014         credit_card                 Credit card refinancing
317245      major_purchase                          Major purchase
367452  debt_consolidation                      Debt consolidation
254591  debt_consolidation                      Debt consolidation
179183         credit_card                 Consolidation of Credit
80805   debt_consolidation                      Debt Consolidation
417188  debt_consolidation                      Debt consolidation
451811  debt_consolidation                      Debt consolidation
297201  debt_consolidation                      Debt consolidation
348572         credit_card                 Credit card refinancing

In [ ]:
df['title']=df['title'].str.lower()

In [ ]:
df['loan_status'].value_counts()

loan_status
Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       761
Name: count, dtype: int64

In [ ]:
df['loan_status'].value_counts(normalize=True)*100

loan_status
Current                                                48.087757
Fully Paid                                             39.619332
Charged Off                                             9.109236
Late (31-120 days)                                      1.479782
In Grace Period                                         0.674695
Does not meet the credit policy. Status:Fully Paid      0.426349
Late (16-30 days)                                       0.261214
Default                                                 0.178432
Does not meet the credit policy. Status:Charged Off     0.163205
Name: proportion, dtype: float64

In [ ]:
df['default']=np.where(df.loc[:,'loan_status'].isin(['Current','Fully Paid','Does not meet the credit policy. Status:Fully Paid','Late (16-30 days)','In Grace Period']),0,1)

In [ ]:
df.sample(100)

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default
287265,14150,14150,60 months,23.43,402.40,F,personalbanker,5 years,MORTGAGE,45000.00,Not Verified,Oct-14,Current,debt_consolidation,debt consolidation,FL,23.51,0.0,May-09,1.0,32.0,NaN,29.0,0.0,11474,45.5,42.0,w,11982.47,6017.580000,2167.53,3850.05,0.000000,0.00,0.0000,Jan-16,402.40,Feb-16,Jan-16,0.0,NaN,0.0,0.0,207482.0,25200.0,0
101090,2500,2500,36 months,15.22,86.94,C,Armstrong Atlantic,3 years,OWN,36000.00,Not Verified,Aug-13,Current,major_purchase,major purchase,GA,12.00,0.0,Jan-05,1.0,NaN,NaN,6.0,0.0,2990,54.4,23.0,f,578.82,2520.840000,1921.18,599.66,0.000000,0.00,0.0000,Jan-16,86.94,Feb-16,Jan-16,0.0,NaN,0.0,0.0,141592.0,5500.0,0
21055,25000,25000,36 months,17.14,893.07,E,Lee dee wholesale,4 years,MORTGAGE,100000.00,Source Verified,Jan-11,Fully Paid,debt_consolidation,debt consolidation loan,LA,20.54,0.0,Jan-93,0.0,NaN,NaN,9.0,0.0,33156,97.2,21.0,f,0.00,31882.400000,25000.00,6882.40,0.000000,0.00,0.0000,Jul-13,6026.03,NaN,Jan-16,0.0,NaN,0.0,NaN,NaN,NaN,0
287780,20000,20000,36 months,19.52,738.39,E,Equipment Specialist,10+ years,MORTGAGE,71000.00,Source Verified,Oct-14,Late (31-120 days),debt_consolidation,debt consolidation,UT,27.19,0.0,Aug-96,2.0,NaN,NaN,9.0,0.0,35790,81.3,21.0,f,15081.09,8806.460000,4918.91,3887.55,0.000000,0.00,0.0000,Dec-15,738.39,Feb-16,Jan-16,0.0,NaN,0.0,0.0,218820.0,44000.0,1
259786,12000,12000,36 months,8.19,377.09,A,security officer,3 years,MORTGAGE,45000.00,Source Verified,Nov-14,Current,debt_consolidation,debt consolidation,CT,11.55,0.0,Apr-98,0.0,35.0,NaN,11.0,0.0,3528,11.7,26.0,f,7678.90,5268.340000,4321.10,947.24,0.000000,0.00,0.0000,Jan-16,377.09,Feb-16,Jan-16,0.0,35.0,0.0,194.0,211079.0,30100.0,0
339755,21175,21175,36 months,16.99,754.85,D,personal banker,2 years,RENT,53000.00,Verified,Jul-14,Fully Paid,debt_consolidation,debt consolidation,PA,7.07,0.0,Jan-09,2.0,NaN,NaN,4.0,0.0,13559,86.9,6.0,f,0.00,23219.340000,21175.00,2044.34,0.000000,0.00,0.0000,Feb-15,18690.24,NaN,Sep-15,0.0,NaN,0.0,0.0,13559.0,15600.0,0
33775,15800,15800,36 months,11.14,518.30,B,Head Start Telecom,< 1 year,OWN,100000.00,Not Verified,Dec-09,Fully Paid,debt_consolidation,credit card payoff,OK,21.88,0.0,Apr-97,0.0,NaN,NaN,7.0,0.0,29860,47.6,22.0,f,0.00,17801.870000,15799.99,2001.88,0.000000,0.00,0.0000,May-11,9511.23,NaN,Jan-16,0.0,NaN,0.0,NaN,NaN,NaN,0
108046,21350,21350,60 months,11.55,470.08,B,Unilever HPC USA,10+ years,RENT,47737.00,Source Verified,Aug-13,Fully Paid,debt_consolidation,dept consolidation,MO,17.22,0.0,Jul-96,0.0,NaN,NaN,8.0,0.0,21298,55.3,16.0,f,0.00,23985.395350,21350.00,2635.40,0.000000,0.00,0.0000,Oct-14,17875.80,NaN,Oct-14,0.0,NaN,0.0,0.0,153086.0,38500.0,0
462312,35000,35000,36 months,13.53,1188.25,B,Software Support,5 years,MORTGAGE,80000.00,Verified,Jan-14,Current,debt_consolidation,credit consolidation,FL,31.04,0.0,Sep-87,0.0,NaN,NaN,16.0,0.0,34764,58.5,47.0,f,13266.78,28517.520000,21733.22,6784.30,0.000000,0.00,0.0000,Jan-16,1188.25,Feb-16,Jan-16,0.0,NaN,0.0,0.0,215011.0,59400.0,0
58545,17800,17800,60 months,18.55,457.35,D,Hygienist,10+ years,MORTGAGE,65000.00,Source Verified,Nov-13,Current,credit_card,regroup,GA,16.67,0.0,May-98,1.0,NaN,NaN,9.0,0.0,22637,79.7,25.0,f,12292.18,11430.990000,5507.82,5923.17,0.000000,0.00,0.0000,Dec-15,457.35,Feb-16,Jan-16,0.0,NaN,0.0,0.0,198025.0,28400.0,0
72460,10000,10000,36 months,16.20,352.56,C,Deli Mgr,10+ years,MORTGAGE,40000.00,Not Verified,Oct-13,Current,credit_card,refi,IL,10.17,1.0,Nov-02,3.0,20.0,NaN,12.0,0.0,9384,68.5,25.0,f,3274.37,9166.050000,6725.63,2440.42,0.000000,0.00,0.0000,Jan-16,352.56,Jan-16,Jan-16,0.0,21.0,0.0,0.0,143719.0,13700.0,0
11764,16000,16000,36 months,13.99,546.77,C,lisi aerospace/hi-shear,3 years,RENT,50000.00,Source Verified,Jul-11,Charged Off,debt_consolidation,debt consolidation loan,CA,16.75,0.0,Dec-02,1.0,56.0,NaN,12.0,0.0,3020,40.3,25.0,f,0.00,5644.310000,3390.61,1520.33,0.000000,733.37,6.9800,May-12,546.77,NaN,Sep-12,0.0,NaN,0.0,NaN,NaN,NaN,1
301028,24000,24000,36 months,7.69,748.65,A,senior client service manager,4 years,RENT,89000.00,Verified,Oct-14,Current,credit_card,credit card refinancing,WA,34.60,0.0,Sep-99,0.0,NaN,NaN,21.0,0.0,48906,82.6,27.0,w,14665.66,11229.750000,9334.34,1895.41,0.000000,0.00,0.0000,Jan-16,748.65,Feb-16,Jan-16,0.0,NaN,0.0,0.0,71382.0,59200.0,0
111426,12000,12000,36 months,16.78,426.52,C,City Erectors Inc.,10+ years,OWN,55000.00,Verified,Jul-13,Current,debt_consolidation,debt consolidation,NJ,13.29,0.0,Feb-83,0.0,48.0,NaN,8.0,0.0,16738,96.8,13.0,f,2829.71,12362.240000,9170.29,3191.95,0.000000,0.00,0.0000,Jan-16,426.52,Jan-16,Jan-16,0.0,NaN,0.0,0.0,18185.0,17300.0,0
250635,20000,20000,60 months,12.99,454.96,C,Physician Assistant,10+ years,MORTGAGE,145000.00,Verified,Nov-14,Current,medical,medical expenses,MI,35.05,0.0,Nov-84,0.0,NaN,NaN,25.0,0.0,133964,88.3,49.0,w,16690.46,5885.610000,3309.54,2576.07,0.000000,0.00,0.0000,Jan-16,454.96,Feb-16,Jan-16,0.0,NaN,0.0,0.0,383998.0,151800.0,0
10446,12000,12000,36 months,11.49,395.66,B,The Walt Disney Company,4 years,MORTGAGE,87600.00,Not Verified,Aug-11,Fully Paid,debt_consolidation,debt consolidation,CA,17.73,0.0,Sep-72,0.0,NaN,NaN,9.0,0.0,38342,93.5,24.0,f,0.00,14242.068570,12000.00,2242.07,0.000000,0.00,0.0000,Aug-14,402.07,NaN,Jan-16,0.0,NaN,0.0,NaN,NaN,NaN,0
292480,15725,15725,36 months,13.35,532.50,C,Developer Advisor,7 years,RENT,114295.98,Verified,Oct-14,Fully Paid,debt_consolidation,debt consolidation,NV,7.75,0.0,Dec-98,0.0,NaN,113.0,11.0,1.0,11460,70.3,12.0,w,0.00,17683.920000,15725.00,1958.92,0.000000,0.00,0.0000,Nov-15,11293.92,NaN,Nov-15,0.0,NaN,0.0,814.0,16368.0,16300.0,0
52508,30000,30000,36 months,14.98,1039.67,C,Journeyman,7 years,OWN,77000.00,Verified,Dec-13,Current,debt_consolidation,debt consolidation,WV,16.85,0.0,Oct-04,1.0,57.0,NaN,8.0,0.0,23388,90.3,16.0,f,10625.92,25916.960000,19374.08,6542.88,0.000000,0.00,0.0000,Jan-16,1039.67,Feb-16,Jan-16,0.0,NaN,0.0,0.0,35392.0,25900.0,0
132968,10000,10000,36 months,22.47,384.35,E,NARDIN PARK RECOVERY CENTER,10+ years,MORTGAGE,120000.00,Verified,Jun-13,Current,debt_consolidation,debt free,MI,13.55,2.0,Feb-91,3.0,7.0,NaN,12.0,0.0,8161,73.5,24.0,w,1817.89,11914.850000,8182.11,3732.74,0.000000,0.00,0.0000,Jan-16,384.35,Feb-16,Jan-16,0.0,49.0,0.0,80.0,22218.0,11100.0,0
170577,12000,12000,36 months,14.09,410.66,B,Cracker Barrel,2 years,MORTGAGE,47500.00,Verified,Jan-13,Current,debt_consolidation,debt/home improvement,PA,33.80,0.0,Sep-03,2.0,44.0,NaN,22.0,0.0,12366,59.7,34.0,w,405.73,14373.100000,11594.27,2778.83,0.000000,0.00,0.0000,Dec-15,410.66,Feb-16,Jan-16,0.0,54.0,0.0,0.0,206232.0,20700.0,0
197748,29700,29700,36 months,8.90,943.08,A,Tom Cat Bakery,5 years,MORTGAGE,100000.00,Source Verified,Sep-12,Fully Paid,home_improvement,multi-family building construction,NY,7.92,0.0,Jul-07,2.0,NaN,NaN,15.0,0.0,11,0.1,22.0,f,0.00,33877.810950,29700.00,4177.81,0.000000,0.00,0.0000,Apr-15,5593.40,NaN,Jan-16,0.0,NaN,0.0,0.0,496532.0,16700.0,0
55041,16000,16000,60 months,12.99,363.97,B,Software Engineer,3 years,MORTGAGE,52000.00,Source Verified,Dec-13,Current,debt_consolidation,debt consolidation,WI,23.63,0.0,Oct-04,0.0,NaN,NaN,16.0,0.0,5810,28.9,30.0,w,10562.39,9111.490000,5437.61,3655.68,18.200000,0.00,0.0000,Jan-16,363.97,Feb-16,Jan-16,0.0,NaN,0.0,0.0,197558.0,20100.0,0
40640,10000,10000,36 months,14.96,346.47,D,NaN,2 years,MORTGAGE,63000.00,Not Verified,Mar-10,Does not meet the credit policy. Status:Charge...,debt_consolidation,bundle payments,FL,11.50,1.0,Jun-81,5.0,14.0,47.0,4.0,1.0,3035,29.5,10.0,f,0.00,2131.000000,1133.45,593.55,0.000000,404.00,4.0000,Aug-10,346.47,Jan-11,Jan-11,0.0,NaN,0.0,NaN,NaN,NaN,1
44282,18500,18500,36 months,14.47,636.52,C,Special Event Coordinator,10+ years,RENT,56500.00,Not Verified,Dec-13,Current,debt_consolidation,debt consolidation,MN,10.30,0.0,Feb-99,1.0,34.0,NaN,10.0,0.0,17561,74.7,24.0,f,6444.83,15876.430000,12055.17,3821.26,0.000000,0.00,0.0000,Jan-16,636.52,Jan-16,Jan-16,0.0,NaN,0.0,0.0,33127.0,23500.0,0
290110,23000,23000,36 months,7.69,717.46,A,OWNER,10+ years,OWN,90000.00,Source Verified,Oct-14,Current,debt_consolidation,debt consolidation,TX,5.26,0.0,Jul-95,0.0,NaN,NaN,17.0,0.0,25398,27.5,47.0,w,14054.53,10752.070000,8945.47,1806.60,0.000000,0.00,0.0000,Jan-16,717.46,Feb-16,Jan-16,0.0,NaN,0.0,0.0,25776.0,92200.0,0
265802,35000,35000,60 months,15.61,843.90,D,Operations Manager,2 years,MORTGAGE,95000.00,Source Verified,Oct-14,Current,debt_consolidation,debt consolidation,CA,13.64,0.0,Aug-82,0.0,51.0,26.0,9.0,1.0,31514,49.1,20.0,w,29074.65,11784.250000,5925.35,5858.90,0.000000,0.00,0.0000,Jan-16,843.90,Jan-16,Jan-16,0.0,51.0,0.0,23740.0,318252.0,64200.0,0
412244,9000,9000,36 months,9.67,289.02,B,Controller,2 years,RENT,54000.00,Not Verified,Apr-14,Current,debt_consolidation,debt consolidation,OH,28.57,0.0,Aug-07,0.0,NaN,NaN,11.0,0.0,12622,79.9,24.0,f,2519.56,7499.420000,6480.44,1018.98,0.000000,0.00,0.0000,Jan-16,289.02,Feb-16,Jan-16,0.0,NaN,0.0,0.0,97972.0,15800.0,0
69103,7000,7000,36 months,9.67,224.79,B,Support Specialist III,3 years,RENT,40000.00,Not Verified,Nov-13,Current,credit_card,credit consolidation payoff,TX,28.05,0.0,Dec-99,3.0,NaN,NaN,5.0,0.0,5589,33.1,15.0,f,2152.02,5843.580000,4847.98,995.60,0.000000,0.00,0.0000,Jan-16,224.79,Feb-16,Jan-16,0.0,NaN,0.0,50.0,40388.0,16900.0,0
270177,9000,9000,36 months,6.49,275.81,A,Vice President,10+ years,RENT,170000.00,Verified,Oct-14,Current,debt_consolidation,debt consolidation,NJ,10.54,0.0,Apr-03,0.0,52.0,NaN,16.0,0.0,12771,39.5,33.0,w,5705.87,3854.850000,3294.13,560.72,0.000000,0.00,0.0000,Dec-15,275.81,Feb-16,Jan-16,0.0,NaN,0.0,0.0,32704.0,32300.0,0
214856,14000,14000,36 months,6.03,426.10,A,"Equanimity, Inc.",9 years,RENT,45000.00,Source Verified,Jun-12,Fully Paid,small_business,small business loan,AZ,14.61,0.0,May-74,0.0,42.0,NaN,11.0,0.0,1860,11.2,26.0,f,0.00,15362.790890,14000.00,1341.48,21.310000,0.00,0.0000,Jul-15,3.08,NaN,Jan-16,0.0,NaN,0.0,NaN,NaN,NaN,0
371103,4000,4000,36 months,15.61,139.86,D,Territory Manager,2 years,RENT,84000.00,Source Verified,Jun-14,Fully Paid,car,car financing,VA,2.46,0.0,Mar-96,2.0,38.0,37.0,8.0,1.0,1629,22.3,46.0,f,0.00,4360.120000,4000.00,360.12,0.000000,0.00,0.0000,Jan-15,3520.96,NaN,May-15,0.0,NaN,0.0,0.0,49732.0,7300.0,0
58303,22000,22000,60 months,23.40,625.26,E,NaN,3 years,OWN,50000.00,Verified,Dec-13,Current,major_purchase,payoff,OH,17.07,1.0,Jun-98,3.0,19.0,NaN,10.0,0.0,6995,69.5,18.0,f,15753.92,15630.860000,6246.08,9384.78,0.000000,0.00,0.0000,Jan-16,625.26,Feb-16,Jan-16,0.0,NaN,0.0,0.0,36245.0,10400.0,0
91181,10000,10000,36 months,10.64,325.69,B,WELLS FARGO ADVISORS,1 year,RENT,72095.00,Verified,Sep-13,Current,debt_consolidation,debt refi,CA,13.73,0.0,Aug-01,0.0,48.0,NaN,9.0,0.0,6262,85.8,23.0,w,2504.36,9119.320000,7495.64,1623.68,0.000000,0.00,0.0000,Jan-16,325.69,Feb-16,Jan-16,0.0,48.0,0.0,0.0,28292.0,7300.0,0
400558,22000,22000,36 months,6.62,675.49,A,Sales,1 year,MORTGAGE,100000.00,Source Verified,Apr-14,Fully Paid,credit_card,credit card refinancing,CT,7.38,0.0,Jun-94,0.0,NaN,NaN,24.0,0.0,40324,24.4,50.0,f,0.00,23379.940000,22000.00,1379.94,0.000000,0.00,0.0000,Jun-15,15274.06,NaN,Jun-15,0.0,NaN,0.0,0.0,350446.0,165300.0,0
133658,30750,30750,60 months,23.63,878.03,F,"Safety-Kleen Systems, Inc",6 years,OWN,100000.00,Verified,Jun-13,Charged Off,other,other,FL,3.04,0.0,Jun-06,1.0,29.0,NaN,9.0,0.0,12155,40.8,11.0,f,0.00,22824.380000,9136.58,13687.80,0.000000,0.00,0.0000,Aug-15,878.03,NaN,Jan-16,0.0,NaN,0.0,0.0,166400.0,29789.0,1
315764,8000,8000,36 months,11.67,264.46,B,Mechanic,7 years,MORTGAGE,38000.00,Not Verified,Aug-14,Fully Paid,debt_consolidation,debt consolidation,FL,6.68,0.0,Mar-09,1.0,NaN,NaN,5.0,0.0,7444,29.9,6.0,f,0.00,8606.150000,8000.00,606.15,0.000000,0.00,0.0000,Apr-15,6754.93,NaN,Jan-16,0.0,NaN,0.0,0.0,7444.0,24900.0,0
174217,10000,10000,36 months,6.62,307.04,A,Ernst & Young,3 years,MORTGAGE,62200.00,Not Verified,Jan-13,Fully Paid,debt_consolidation,credit card consolidation,GA,14.97,0.0,Oct-05,2.0,NaN,NaN,14.0,0.0,12054,27.0,22.0,f,0.00,10953.446200,10000.00,953.45,0.000000,0.00,0.0000,Feb-15,3598.40,NaN,Feb-15,0.0,NaN,0.0,0.0,218103.0,44600.0,0
372746,12000,12000,36 months,13.35,406.36,C,Production Assistant,10+ years,RENT,47684.00,Source Verified,Jun-14,Late (16-30 days),other,other,TX,24.54,0.0,Jul-92,0.0,NaN,69.0,11.0,2.0,6098,80.2,17.0,w,6595.33,7314.480000,5404.67,1909.81,0.000000,0.00,0.0000,Dec-15,406.36,Feb-16,Jan-16,0.0,NaN,0.0,0.0,31481.0,7600.0,1
445929,20000,20000,36 months,8.90,635.07,A,Principal Consultant,10+ years,MORTGAGE,170000.00,Source Verified,Feb-14,Current,car,car financing,PA,13.22,0.0,Jan-00,1.0,NaN,NaN,9.0,0.0,36290,75.3,22.0,f,7842.51,14606.610000,12157.49,2449.12,0.000000,0.00,0.0000,Jan-16,635.07,Feb-16,Jan-16,0.0,NaN,0.0,0.0,327224.0,48200.0,0
366820,15375,15375,36 months,12.49,514.28,B,Warehouse Manager,2 years,RENT,42900.00,Verified,Jun-14,Fully Paid,debt_consolidation,debt consolidation,FL,2.69,0.0,Sep-06,0.0,NaN,NaN,12.0,0.0,1942,53.9,14.0,w,0.00,17186.720000,15374.99,1811.73,0.000000,0.00,0.0000,Jan-16,441.28,NaN,Jan-16,0.0,NaN,0.0,0.0,40606.0,3600.0,0
136985,12000,12000,36 months,15.31,417.81,C,Ellison Investments,4 years,MORTGAGE,88000.00,Source Verified,May-13,Charged Off,debt_consolidation,getdebtfree,TX,14.96,1.0,Jan-08,2.0,7.0,NaN,10.0,0.0,5358,31.9,18.0,f,0.00,3207.350000,1079.10,591.86,0.000000,1536.39,15.3639,Sep-13,417.81,NaN,Feb-14,0.0,NaN,0.0,0.0,123136.0,16800.0,1
217680,24000,24000,60 months,20.50,642.55,E,Scitor,2 years,MORTGAGE,138000.00,Source Verified,May-12,Fully Paid,debt_consolidation,consolidation,VA,17.58,0.0,Dec-92,1.0,46.0,NaN,17.0,0.0,31184,74.4,33.0,f,0.00,36166.815860,24000.00,12166.82,0.000000,0.00,0.0000,Jul-15,12423.97,NaN,Jul-15,0.0,NaN,0.0,NaN,NaN,NaN,0
409,2000,2000,36 months,7.90,62.59,A,Jpmorgan Chase,4 years,RENT,39600.00,Not Verified,Dec-11,Fully Paid,credit_card,refi,CA,5.09,0.0,Oct-98,0.0,NaN,NaN,8.0,0.0,2058,79.2,13.0,f,0.00,2252.269997,2000.00,252.27,0.000000,0.00,0.0000,Dec-14,65.78,NaN,Sep-15,0.0,NaN,0.0,NaN,NaN,NaN,0
258564,12500,12500,36 months,12.99,421.12,C,Sales,1 year,RENT,50000.00,Not Verified,Nov-14,Current,debt_consolidation,debt consolidation,CA,14.07,0.0,Dec-08,0.0,NaN,NaN,5.0,0.0,1497,22.7,10.0,w,8204.59,5886.660000,4295.41,1591.25,0.000000,0.00,0.0000,Jan-16,421.12,Feb-16,Jan-16,0.0,NaN,0.0,0.0,18681.0,6600.0,0
42981,26250,26250,60 months,12.85,595.26,B,Operations Manager,5 years,MORTGAGE,70000.00,Verified,Dec-13,Current,debt_consolidation,debt consolidation,TX,14.32,0.0,Sep-94,0.0,NaN,NaN,9.0,0.0,14328,56.0,20.0,f,17705.71,14283.570000,8544.29,5739.28,0.000000,0.00,0.0000,Jan-16,595.26,Feb-16,Jan-16,0.0,NaN,0.0,0.0,149367.0,25600.0,0
29886,17000,11000,60 months,7.88,222.41,A,black box corp,8 years,MORTGAGE,35000.00,Not Verified,May-10,Fully Paid,home_improvement,home improvement,PA,9.94,0.0,Sep-90,0.0,NaN,NaN,9.0,0.0,11,0.0,28.0,f,0.00,13340.763790,11000.00,2340.76,0.000000,0.00,0.0000,Jun-15,235.73,NaN,May-15,0.0,NaN,0.0,NaN,NaN,NaN,0
326337,18000,18000,60 months,14.99,428.13,C,lead of departent,10+ years,OWN,40000.00,Source Verified,Aug-14,Current,debt_consolidation,debt consolidation,TX,11.40,0.0,Mar-90,0.0,NaN,107.0,7.0,1.0,18506,26.8,15.0,f,14176.35,7278.210000,3823.65,3454.56,0.000000,0.00,0.0000,Jan-16,428.13,Feb-16,Jan-15,0.0,NaN,0.0,0.0,18506.0,69000.0,0
356036,9000,9000,36 months,10.15,291.04,B,Assistant Manager,10+ years,MORTGAGE,49000.00,Source Verified,Jul-14,Fully Paid,debt_consolidation,debt consolidation,CO,12.03,0.0,Feb-05,0.0,NaN,NaN,6.0,0.0,4772,60.4,13.0,f,0.00,9814.940000,9000.00,814.94,0.000000,0.00,0.0000,Jul-15,6613.50,NaN,Jul-15,0.0,NaN,0.0,0.0,140398.0,7900.0,0
102615,20000,20000,60 months,16.78,494.69,C,Hanover Insurance,10+ years,MORTGAGE,54000.00,Verified,Aug-13,Current,debt_consolidation,rescue,MI,23.84,0.0,Aug-95,0.0,26.0,NaN,10.0,0.0,19352,75.0,21.0,w,12374.96,14346.010000,7625.04,6720.97,0.000000,0.00,0.0000,Jan-16,494.69,Feb-16,Jan-16,0.0,NaN,0.0,0.0,190151.0,25800.0,0
54514,7750,7750,36 months,15.61,270.98,C,Account manager,10+ years,RENT,30000.00,Source Verified,Dec-13,Charged Off,debt_consolidation,debt loan,OH,25.76,0.0,Jul-07,0.0,NaN,NaN,6.0,0.0,8358,46.4,9.0,f,0.00,2438.740000,1613.59,825.15,0.000000,0.00,0.0000,Oct-14,270.98,NaN,Jan-16,0.0,NaN,0.0,0.0,8358.0,18000.0,1
374769,23000,23000,36 months,12.49,769.33,B,Research Scientist,< 1 year,MORTGAGE,195000.00,Source Verified,Jun-14,Current,debt_consolidation,debt consolidation,TX,25.75,0.0,Mar-78,4.0,35.0,NaN,25.0,0.0,93690,75.8,58.0,w,12572.37,13847.940000,10427.63,3420.31,0.000000,0.00,0.0000,Jan-16,769.33,Feb-16,Jan-16,0.0,NaN,0.0,633.0,464165.0,123600.0,0
409385,23000,23000,60 months,15.31,550.92,C,machinist,9 years,MORTGAGE,68000.00,Source Verified,Apr-14,Current,debt_consolidation,debt consolidation,PA,9.20,1.0,Aug-00,0.0,18.0,NaN,7.0,0.0,2098,77.7,19.0,w,16844.02,11569.320000,6155.98,5413.34,0.000000,0.00,0.0000,Jan-16,550.92,Feb-16,Jan-16,0.0,NaN,0.0,116.0,58321.0,2700.0,0
77771,2500,2500,36 months,17.76,90.09,D,Manager-Director of Tennis,10+ years,RENT,48000.00,Source Verified,Oct-13,Current,credit_card,irs tax return loan,CA,29.58,2.0,Dec-96,0.0,11.0,NaN,8.0,0.0,13374,73.5,17.0,w,753.53,2432.430000,1746.47,685.96,0.000000,0.00,0.0000,Jan-16,90.09,Feb-16,Jan-16,0.0,11.0,0.0,0.0,31757.0,18200.0,0
16617,4000,4000,36 months,12.68,134.17,C,NYPD,4 years,RENT,75000.00,Source Verified,Apr-11,Fully Paid,vacation,catch up,NY,19.42,1.0,Nov-99,0.0,14.0,NaN,7.0,0.0,4668,86.4,24.0,f,0.00,4789.480000,4000.00,789.48,0.000000,0.00,0.0000,Oct-13,1042.54,NaN,Oct-13,0.0,NaN,0.0,NaN,NaN,NaN,0
128062,10000,10000,36 months,17.77,360.38,D,Multi-Phase Electrical Services INC,1 year,RENT,75000.00,Not Verified,Jun-13,Fully Paid,debt_consolidation,debt consolidation,NJ,21.55,1.0,Oct-99,2.0,23.0,NaN,23.0,0.0,9661,23.7,39.0,f,0.00,11215.484890,10000.00,1215.48,0.000000,0.00,0.0000,Mar-14,8332.68,NaN,Jan-16,0.0,NaN,0.0,0.0,58314.0,40700.0,0
26817,8000,8000,60 months,13.98,186.07,C,United States Army,10+ years,MORTGAGE,72000.00,Source Verified,Aug-10,Fully Paid,small_business,business loan,OK,17.61,1.0,Jun-96,0.0,20.0,106.0,11.0,1.0,44856,74.1,19.0,f,0.00,11171.856570,8000.00,3156.88,14.972591,0.00,0.0000,Jul-15,379.66,NaN,Jan-16,0.0,NaN,0.0,NaN,NaN,NaN,0
383188,16000,16000,60 months,12.99,363.97,C,store manager,2 years,RENT,69000.00,Source Verified,May-14,Fully Paid,debt_consolidation,debt consolidation,WA,18.83,0.0,Aug-06,1.0,NaN,NaN,10.0,0.0,3590,21.6,13.0,w,0.00,17466.950000,16000.00,1466.95,0.000000,0.00,0.0000,Feb-15,14919.16,NaN,Feb-15,0.0,NaN,0.0,0.0,29834.0,16600.0,0
263448,16000,16000,36 months,6.03,486.97,A,IB Coordinator,10+ years,MORTGAGE,85000.00,Source Verified,Nov-14,Fully Paid,debt_consolidation,debt consolidation,IL,11.24,0.0,Jul-01,0.0,NaN,NaN,17.0,0.0,7146,14.6,60.0,f,0.00,16163.580000,16000.00,163.58,0.000000,0.00,0.0000,Jan-15,15681.97,NaN,Jan-16,0.0,NaN,0.0,0.0,623656.0,49100.0,0
337917,24000,24000,36 months,16.29,847.21,D,Foreman,10+ years,RENT,105000.00,Source Verified,Aug-14,Current,debt_consolidation,debt consolidation,WA,14.54,1.0,Sep-90,0.0,12.0,NaN,11.0,0.0,31390,92.3,19.0,w,14104.85,14429.270000,9895.15,4534.12,0.000000,0.00,0.0000,Jan-16,873.91,Feb-16,Jan-16,0.0,NaN,0.0,0.0,49297.0,34000.0,0

In [ ]:
# According to our classification we get around 12% as defaulters and 88% as non-defaulters.
df['default'].value_counts(normalize=True)*100

default
0    88.133438
1    11.866562
Name: proportion, dtype: float64

## THE MOST IMPORTANT COLUMNS FOR CREDIT RISK MODELLING PURPOSE-

### DEMOGRAPHIC COLUMNS-

 addr_state-The state provided by the borrower in the loan application

 annual_inc- The self-reported annual income provided by the borrower during registration.

 emp_length-Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.

 home_ownership-The home ownership status provided by the borrower during registration. Our values are: RENT, OWN, MORTGAGE, OTHER.

In [ ]:
df.shape

(466285, 46)

1. FEATURES REMOVAL
*  removed those columns which had 100% missing value
*  new feature named good_loan
    *   1 - non default
    *   0 - default

*  remove sub groups
2. DATA TYPE CORRECTION

working on columns :
emp_length,
term,
issue_d,
last_pymnt_d,
last_credit_pull_d
earliest_cr_line

In [ ]:
df.sample()

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default
279697,4200,4200,36 months,14.49,144.55,C,Table Games Dealer,2 years,RENT,45000.0,Source Verified,Oct-14,Current,debt_consolidation,debt consolidation,CA,8.61,0.0,May-00,3.0,59.0,82.0,9.0,1.0,4846,86.5,18.0,f,2667.05,2164.87,1532.95,631.92,0.0,0.0,0.0,Jan-16,144.55,Feb-16,Jan-16,0.0,NaN,0.0,0.0,5294.0,5600.0,0

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# changing datatype of term from object to int
df['term']=df['term'].str.replace('months','').astype(int)

In [ ]:
df['term'].isnull().sum()

np.int64(0)

In [ ]:
df.sample()

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default
265222,5375,5375,36,18.99,197.0,E,General Manager,10+ years,RENT,51000.0,Not Verified,Nov-14,Current,moving,moving and relocation,CA,8.35,1.0,Jul-02,0.0,NaN,23.0,3.0,1.0,396,16.0,9.0,w,3635.97,2743.82,1739.03,1004.79,0.0,0.0,0.0,Jan-16,197.0,Feb-16,Jan-16,0.0,24.0,0.0,0.0,9023.0,2440.0,0

In [ ]:
#emp_length
df['emp_length'].value_counts()

emp_length
10+ years    150049
2 years       41373
3 years       36596
< 1 year      36265
5 years       30774
1 year        29622
4 years       28023
7 years       26180
6 years       26112
8 years       22395
9 years       17888
Name: count, dtype: int64

In [ ]:
df['emp_length'].isnull().sum()

np.int64(21008)

In [ ]:
df['emp_length']=df['emp_length'].str.replace('+ years','').str.strip()
df['emp_length']=df['emp_length'].str.replace('years','').str.strip()
df['emp_length']=df['emp_length'].str.replace('1 year','1').str.strip()
df['emp_length']=df['emp_length'].str.replace('< 1 year',str(0)).str.strip()
df['emp_length']=df['emp_length'].str.replace('< 1',str(0)).str.strip()

In [ ]:
df['emp_length']=df['emp_length'].fillna(0)

In [ ]:
df['emp_length'].unique()

array(['10', '0', '1', '3', '8', '9', '4', '5', '6', '2', '7', 0],
      dtype=object)

In [ ]:
df['emp_length'].value_counts()

emp_length
10    150049
2      41373
3      36596
0      36265
5      30774
1      29622
4      28023
7      26180
6      26112
8      22395
0      21008
9      17888
Name: count, dtype: int64

In [ ]:
df['emp_length']=df['emp_length'].astype(int)

In [ ]:
#df['emp_length']=pd.to_numeric(df['emp_length'])

In [ ]:
df.head()

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default
0,5000,5000,36,10.65,162.87,B,NaN,10,RENT,24000.0,Verified,Dec-11,Fully Paid,credit_card,computer,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,5861.071414,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,0.0,NaN,NaN,NaN,0
1,2500,2500,60,15.27,59.83,C,Ryder,0,RENT,30000.0,Source Verified,Dec-11,Charged Off,car,bike,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,1008.710000,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,0.0,NaN,NaN,NaN,1
2,2400,2400,36,15.96,84.33,C,NaN,10,RENT,12252.0,Not Verified,Dec-11,Fully Paid,small_business,real estate business,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,3003.653644,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,0.0,NaN,NaN,NaN,0
3,10000,10000,36,13.49,339.31,C,AIR RESOURCES BOARD,10,RENT,49200.0,Source Verified,Dec-11,Fully Paid,other,personel,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,12226.302210,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,0.0,NaN,NaN,NaN,0
4,3000,3000,60,12.69,67.79,B,University Medical Group,1,RENT,80000.0,Source Verified,Dec-11,Current,other,personal,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,3242.170000,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,0.0,NaN,NaN,NaN,0

In [ ]:
df['earliest_cr_line']=pd.to_datetime(df['earliest_cr_line'],format='%b-%y')

In [ ]:
df['earliest_cr_line'].sample(2)

84260    1991-06-01
154117   1993-01-01
Name: earliest_cr_line, dtype: datetime64[ns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 46 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466285 non-null  int64
 1   funded_amnt                  466285 non-null  int64
 2   term                         466285 non-null  int64
 3   int_rate                     466285 non-null  float64
 4   installment                  466285 non-null  float64
 5   grade                        466285 non-null  object
 6   emp_title                    438697 non-null  object
 7   emp_length                   466285 non-null  int64
 8   home_ownership               466285 non-null  object
 9   annual_inc                   466281 non-null  float64
 10  verification_status          466285 non-null  object
 11  issue_d                      466285 non-null  object
 12  loan_status                  466285 non-null  object
 13  purpose                      466285 non-null  object
 14  title                        466264 non-null  object
 15  addr_state                   466285 non-null  object
 16  dti                          466285 non-null  float64
 17  delinq_2yrs                  466256 non-null  float64
 18  earliest_cr_line             466256 non-null  datetime64[ns]
 19  inq_last_6mths               466256 non-null  float64
 20  mths_since_last_delinq       215934 non-null  float64
 21  mths_since_last_record       62638 non-null   float64
 22  open_acc                     466256 non-null  float64
 23  pub_rec                      466256 non-null  float64
 24  revol_bal                    466285 non-null  int64
 25  revol_util                   465945 non-null  float64
 26  total_acc                    466256 non-null  float64
 27  initial_list_status          466285 non-null  object
 28  out_prncp                    466285 non-null  float64
 29  total_pymnt                  466285 non-null  float64
 30  total_rec_prncp              466285 non-null  float64
 31  total_rec_int                466285 non-null  float64
 32  total_rec_late_fee           466285 non-null  float64
 33  recoveries                   466285 non-null  float64
 34  collection_recovery_fee      466285 non-null  float64
 35  last_pymnt_d                 465909 non-null  object
 36  last_pymnt_amnt              466285 non-null  float64
 37  next_pymnt_d                 239071 non-null  object
 38  last_credit_pull_d           466243 non-null  object
 39  collections_12_mths_ex_med   466140 non-null  float64
 40  mths_since_last_major_derog  98974 non-null   float64
 41  acc_now_delinq               466256 non-null  float64
 42  tot_coll_amt                 396009 non-null  float64
 43  tot_cur_bal                  396009 non-null  float64
 44  total_rev_hi_lim             396009 non-null  float64
 45  default                      466285 non-null  int64
dtypes: datetime64[ns](1), float64(26), int64(6), object(13)
memory usage: 163.6+ MB

In [ ]:
# filling the missing values with unknown
df['emp_title']=df['emp_title'].fillna('unknown')
df['emp_title']=df['emp_title'].str.lower()

In [ ]:
#dropping 4 rows from the datset as annual_inc along with majority of columns are zero
#also it falls in good loan category to
df[df['annual_inc'].isna()]

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default
42449,5000,5000,36,7.43,155.38,A,unknown,0,NONE,NaN,Not Verified,Aug-07,Does not meet the credit policy. Status:Fully ...,other,moving expenses,NY,1.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,5593.46,5000.0,593.46,0.0,0.0,0.0,Aug-10,157.31,Sep-10,May-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42450,7000,7000,36,7.75,218.55,A,unknown,0,NONE,NaN,Not Verified,Aug-07,Does not meet the credit policy. Status:Fully ...,other,education,NY,1.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,7867.53,7000.0,867.53,0.0,0.0,0.0,Aug-10,220.03,Sep-10,May-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42480,6700,6700,36,7.75,209.18,A,unknown,0,NONE,NaN,Not Verified,Jul-07,Does not meet the credit policy. Status:Fully ...,other,moving expenses and security deposit,NY,1.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,7530.42,6700.0,830.42,0.0,0.0,0.0,Jul-10,209.89,Aug-10,May-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42533,6500,6500,36,8.38,204.84,A,unknown,0,NONE,NaN,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,buying a car,NY,4.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,7373.83,6500.0,873.83,0.0,0.0,0.0,Jun-10,205.32,Jul-10,Aug-07,NaN,NaN,NaN,NaN,NaN,NaN,0

In [ ]:
#for checking the loan status of the rows that we will remove.
df[df['annual_inc'].isna()]['loan_status']

42449    Does not meet the credit policy. Status:Fully ...
42450    Does not meet the credit policy. Status:Fully ...
42480    Does not meet the credit policy. Status:Fully ...
42533    Does not meet the credit policy. Status:Fully ...
Name: loan_status, dtype: object

In [ ]:
df=df[~df['annual_inc'].isna()]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 466281 entries, 0 to 466284
Data columns (total 46 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466281 non-null  int64
 1   funded_amnt                  466281 non-null  int64
 2   term                         466281 non-null  int64
 3   int_rate                     466281 non-null  float64
 4   installment                  466281 non-null  float64
 5   grade                        466281 non-null  object
 6   emp_title                    466281 non-null  object
 7   emp_length                   466281 non-null  int64
 8   home_ownership               466281 non-null  object
 9   annual_inc                   466281 non-null  float64
 10  verification_status          466281 non-null  object
 11  issue_d                      466281 non-null  object
 12  loan_status                  466281 non-null  object
 13  purpose                      466281 non-null  object
 14  title                        466260 non-null  object
 15  addr_state                   466281 non-null  object
 16  dti                          466281 non-null  float64
 17  delinq_2yrs                  466256 non-null  float64
 18  earliest_cr_line             466256 non-null  datetime64[ns]
 19  inq_last_6mths               466256 non-null  float64
 20  mths_since_last_delinq       215934 non-null  float64
 21  mths_since_last_record       62638 non-null   float64
 22  open_acc                     466256 non-null  float64
 23  pub_rec                      466256 non-null  float64
 24  revol_bal                    466281 non-null  int64
 25  revol_util                   465945 non-null  float64
 26  total_acc                    466256 non-null  float64
 27  initial_list_status          466281 non-null  object
 28  out_prncp                    466281 non-null  float64
 29  total_pymnt                  466281 non-null  float64
 30  total_rec_prncp              466281 non-null  float64
 31  total_rec_int                466281 non-null  float64
 32  total_rec_late_fee           466281 non-null  float64
 33  recoveries                   466281 non-null  float64
 34  collection_recovery_fee      466281 non-null  float64
 35  last_pymnt_d                 465905 non-null  object
 36  last_pymnt_amnt              466281 non-null  float64
 37  next_pymnt_d                 239067 non-null  object
 38  last_credit_pull_d           466239 non-null  object
 39  collections_12_mths_ex_med   466140 non-null  float64
 40  mths_since_last_major_derog  98974 non-null   float64
 41  acc_now_delinq               466256 non-null  float64
 42  tot_coll_amt                 396009 non-null  float64
 43  tot_cur_bal                  396009 non-null  float64
 44  total_rev_hi_lim             396009 non-null  float64
 45  default                      466281 non-null  int64
dtypes: datetime64[ns](1), float64(26), int64(6), object(13)
memory usage: 167.2+ MB

In [ ]:
# purpose and title are similar columns so dropping title column
df.drop(columns=['title'],inplace=True)

In [ ]:
#checking for null values in delinq_2yrs
df[df['delinq_2yrs'].isna()]

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default
42459,4350,4350,36,8.07,136.45,A,unknown,0,RENT,120000.0,Not Verified,Aug-07,Does not meet the credit policy. Status:Fully ...,other,MA,4.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,4911.68,4350.00,561.68,0.000000,0.00,0.0000,Aug-10,139.93,Sep-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
42472,3900,3900,36,9.33,124.62,B,unknown,0,RENT,98000.0,Not Verified,Aug-07,Does not meet the credit policy. Status:Fully ...,other,NY,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,4485.99,3900.00,585.99,0.000000,0.00,0.0000,Aug-10,126.06,Sep-10,May-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42483,3200,3200,36,9.96,103.20,B,unknown,0,MORTGAGE,150000.0,Not Verified,Jul-07,Does not meet the credit policy. Status:Fully ...,other,MA,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,3590.53,3200.00,390.53,0.000000,0.00,0.0000,Feb-09,1733.32,Mar-09,Feb-09,NaN,NaN,NaN,NaN,NaN,NaN,0
42494,7200,5075,36,10.28,164.42,C,unknown,0,RENT,95000.0,Not Verified,Jul-07,Does not meet the credit policy. Status:Fully ...,other,NY,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,5918.33,5075.00,843.33,0.000000,0.00,0.0000,Jul-10,168.44,Aug-10,May-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42509,1900,1900,36,9.64,61.00,B,scheduall,1,MORTGAGE,100000.0,Not Verified,Jul-07,Does not meet the credit policy. Status:Fully ...,debt_consolidation,FL,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,1999.12,1900.00,99.12,0.000000,0.00,0.0000,Feb-08,0.00,Feb-08,May-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42514,1200,1200,36,9.01,38.17,B,classic components,0,RENT,36000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,TX,3.27,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,1373.88,1200.00,173.88,0.000000,0.00,0.0000,Jul-10,39.05,Jul-10,Jan-16,NaN,NaN,NaN,NaN,NaN,NaN,0
42515,5000,5000,36,11.22,164.23,C,compensation solutions,0,RENT,28000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,NJ,3.51,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,5858.35,5000.00,828.36,29.994759,0.00,0.0000,Apr-10,149.43,Apr-10,Apr-10,NaN,NaN,NaN,NaN,NaN,NaN,0
42516,1400,1400,36,10.91,45.78,C,"stanford university libraries, lockss project",0,RENT,40000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,MO,8.61,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,1663.04,1400.00,248.05,14.994369,0.00,0.0000,Jul-10,1.78,Aug-10,Sep-14,NaN,NaN,NaN,NaN,NaN,NaN,0
42517,1000,1000,36,14.07,34.21,E,macy's,10,RENT,25000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,NJ,16.27,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,1231.38,1000.00,231.38,0.000000,0.00,0.0000,Jun-10,35.27,Jul-10,Jun-10,NaN,NaN,NaN,NaN,NaN,NaN,0
42518,5000,5000,36,7.75,156.11,A,diamond management and technology consultants,10,MORTGAGE,300000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,LA,5.38,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,5565.65,5000.00,565.65,0.000000,0.00,0.0000,Aug-09,1663.91,Sep-09,Aug-09,NaN,NaN,NaN,NaN,NaN,NaN,0
42519,2500,2500,36,7.43,77.69,A,u.s. bank,9,MORTGAGE,66624.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,OH,10.36,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,2600.23,2500.00,100.23,0.000000,0.00,0.0000,Jan-08,0.00,Jan-08,Jun-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42520,3000,3000,36,7.43,93.23,A,nc,1,MORTGAGE,80000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,NJ,0.39,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,3120.26,3000.00,120.26,0.000000,0.00,0.0000,Jan-08,0.00,Jan-08,Jun-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42521,2600,2600,36,8.38,81.94,A,college pro painters,3,MORTGAGE,6500.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Charge...,other,CO,6.46,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,2342.01,1962.69,329.05,21.640000,28.63,0.3400,Mar-10,21.75,Mar-10,Mar-10,NaN,NaN,NaN,NaN,NaN,NaN,1
42522,1000,1000,36,7.12,30.94,A,mana products,6,RENT,50000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,NY,1.10,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,1113.35,1000.00,113.35,0.000000,0.00,0.0000,Jun-10,32.93,Jul-10,Apr-14,NaN,NaN,NaN,NaN,NaN,NaN,0
42523,1275,1275,36,12.49,42.65,D,infinitely law group,1,RENT,40000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Charge...,other,MA,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,1341.96,340.50,128.57,0.000000,872.89,305.5105,May-08,42.65,Dec-08,Jan-16,NaN,NaN,NaN,NaN,NaN,NaN,1
42524,6450,6450,36,11.22,211.85,C,apto solutions,2,RENT,32000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,GA,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,7798.60,6450.00,1228.60,120.000000,0.00,0.0000,Jul-10,167.78,Jul-10,Jun-10,NaN,NaN,NaN,NaN,NaN,NaN,0
42525,10500,10500,36,11.22,344.87,C,town of plainville,3,RENT,60000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,CT,19.50,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,11219.80,10500.00,719.80,0.000000,0.00,0.0000,Aug-08,0.00,Aug-08,Jun-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42526,3000,3000,36,9.01,95.42,B,tanks tavern,0,RENT,35000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,KS,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,3434.97,3000.00,434.97,0.000000,0.00,0.0000,Jul-10,95.66,Jul-10,Jun-10,NaN,NaN,NaN,NaN,NaN,NaN,0
42527,3000,3000,36,9.33,95.86,B,unknown,0,OWN,20000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,MA,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,3450.79,3000.00,450.79,0.000000,0.00,0.0000,Jun-10,96.77,Jul-10,May-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42528,2000,2000,36,9.96,64.50,B,unknown,0,RENT,6000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,FL,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,2322.36,2000.00,322.36,0.000000,0.00,0.0000,Jul-10,0.84,Aug-10,Jul-10,NaN,NaN,NaN,NaN,NaN,NaN,0
42529,6500,6500,36,9.64,208.66,B,air force,0,RENT,20000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Charge...,other,CT,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,7193.05,1791.32,503.81,0.000000,4897.92,1714.2700,May-08,208.65,Dec-08,Jan-16,NaN,NaN,NaN,NaN,NaN,NaN,1
42530,3500,3500,36,10.28,113.39,C,unknown,0,RENT,180000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,NY,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,3719.34,3500.00,219.34,0.000000,0.00,0.0000,Mar-08,0.00,Mar-08,Feb-13,NaN,NaN,NaN,NaN,NaN,NaN,0
42531,1000,1000,36,9.64,32.11,B,halping hands company inc.,0,RENT,12000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,MA,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,1155.53,1000.00,155.53,0.000000,0.00,0.0000,Jun-10,32.41,Jul-10,Sep-14,NaN,NaN,NaN,NaN,NaN,NaN,0
42532,2525,2525,36,9.33,80.69,B,unknown,0,RENT,110000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,NY,10.00,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,2904.30,2525.00,379.30,0.000000,0.00,0.0000,Jun-10,82.03,Jul-10,May-07,NaN,NaN,NaN,NaN,NaN,NaN,0
42534,5000,5000,36,7.75,156.11,A,homemaker,10,MORTGAGE,70000.0,Not Verified,Jun-07,Does not meet the credit policy. Status:Fully ...,other,CT,8.81,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,f,0.0,5619.72,5000.00,619.72,0.000000,0.00,0.0000,Jun-10,156.39,Jul-10,Feb-15,NaN,NaN,NaN,NaN,NaN,NaN,0

In [ ]:
#filling missing values with 0
df['delinq_2yrs']=df['delinq_2yrs'].fillna(0)
#dropping these 2 columns as they contain a lot of missing values and also less important for our models
df.drop(columns=['mths_since_last_delinq','mths_since_last_record'],inplace=True)
df.drop(columns=['next_pymnt_d','mths_since_last_major_derog'],inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 466281 entries, 0 to 466284
Data columns (total 41 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   loan_amnt                   466281 non-null  int64
 1   funded_amnt                 466281 non-null  int64
 2   term                        466281 non-null  int64
 3   int_rate                    466281 non-null  float64
 4   installment                 466281 non-null  float64
 5   grade                       466281 non-null  object
 6   emp_title                   466281 non-null  object
 7   emp_length                  466281 non-null  int64
 8   home_ownership              466281 non-null  object
 9   annual_inc                  466281 non-null  float64
 10  verification_status         466281 non-null  object
 11  issue_d                     466281 non-null  object
 12  loan_status                 466281 non-null  object
 13  purpose                     466281 non-null  object
 14  addr_state                  466281 non-null  object
 15  dti                         466281 non-null  float64
 16  delinq_2yrs                 466281 non-null  float64
 17  earliest_cr_line            466256 non-null  datetime64[ns]
 18  inq_last_6mths              466256 non-null  float64
 19  open_acc                    466256 non-null  float64
 20  pub_rec                     466256 non-null  float64
 21  revol_bal                   466281 non-null  int64
 22  revol_util                  465945 non-null  float64
 23  total_acc                   466256 non-null  float64
 24  initial_list_status         466281 non-null  object
 25  out_prncp                   466281 non-null  float64
 26  total_pymnt                 466281 non-null  float64
 27  total_rec_prncp             466281 non-null  float64
 28  total_rec_int               466281 non-null  float64
 29  total_rec_late_fee          466281 non-null  float64
 30  recoveries                  466281 non-null  float64
 31  collection_recovery_fee     466281 non-null  float64
 32  last_pymnt_d                465905 non-null  object
 33  last_pymnt_amnt             466281 non-null  float64
 34  last_credit_pull_d          466239 non-null  object
 35  collections_12_mths_ex_med  466140 non-null  float64
 36  acc_now_delinq              466256 non-null  float64
 37  tot_coll_amt                396009 non-null  float64
 38  tot_cur_bal                 396009 non-null  float64
 39  total_rev_hi_lim            396009 non-null  float64
 40  default                     466281 non-null  int64
dtypes: datetime64[ns](1), float64(23), int64(6), object(11)
memory usage: 149.4+ MB

In [ ]:
df[df['tot_coll_amt'].isna()].sample()

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default
33666,6000,6000,36,11.83,198.81,B,nexus digital studio,4,RENT,76000.0,Not Verified,Dec-09,Fully Paid,debt_consolidation,CA,3.44,0.0,2000-10-01,0.0,13.0,0.0,7269,38.7,19.0,f,0.0,6696.38,6000.0,696.38,0.0,0.0,0.0,Mar-11,4118.65,Oct-15,0.0,0.0,NaN,NaN,NaN,0

In [ ]:
df.to_csv("loan2.csv")