In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Projects /CREDIT RISK MODELLING/loan3.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466281 entries, 0 to 466280
Data columns (total 53 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   loan_amnt                   466281 non-null  int64
 1   funded_amnt                 466281 non-null  int64
 2   term                        466281 non-null  int64
 3   int_rate                    466281 non-null  float64
 4   installment                 466281 non-null  float64
 5   grade                       466281 non-null  object
 6   emp_title                   466281 non-null  object
 7   emp_length                  466281 non-null  int64
 8   home_ownership              466281 non-null  object
 9   annual_inc                  466281 non-null  float64
 10  verification_status         466281 non-null  object
 11  issue_d                     466281 non-null  object
 12  loan_status                 466281 non-null  object
 13  purpose                     466281 non-null  object
 14  addr_state                  466281 non-null  object
 15  dti                         466281 non-null  float64
 16  delinq_2yrs                 466281 non-null  float64
 17  earliest_cr_line            466281 non-null  object
 18  inq_last_6mths              466281 non-null  float64
 19  open_acc                    466256 non-null  float64
 20  pub_rec                     466256 non-null  float64
 21  revol_bal                   466281 non-null  int64
 22  revol_util                  466281 non-null  float64
 23  total_acc                   466256 non-null  float64
 24  initial_list_status         466281 non-null  object
 25  out_prncp                   466281 non-null  float64
 26  total_pymnt                 466281 non-null  float64
 27  total_rec_prncp             466281 non-null  float64
 28  total_rec_int               466281 non-null  float64
 29  total_rec_late_fee          466281 non-null  float64
 30  recoveries                  466281 non-null  float64
 31  collection_recovery_fee     466281 non-null  float64
 32  last_pymnt_d                465905 non-null  object
 33  last_pymnt_amnt             466281 non-null  float64
 34  last_credit_pull_d          466239 non-null  object
 35  collections_12_mths_ex_med  466140 non-null  float64
 36  acc_now_delinq              466256 non-null  float64
 37  tot_coll_amt                396009 non-null  float64
 38  tot_cur_bal                 466281 non-null  float64
 39  total_rev_hi_lim            466281 non-null  float64
 40  default                     466281 non-null  int64
 41  loan_to_income              466281 non-null  float64
 42  credit_age                  466281 non-null  float64
 43  rev_data_missing            466281 non-null  int64
 44  int_rate_bin                466281 non-null  object
 45  out_prncp_bin               466281 non-null  object
 46  loan_to_income_bin          466281 non-null  object
 47  annual_inc_bin              466281 non-null  object
 48  inq_last_6mths_bin          466281 non-null  object
 49  dti_bin                     466281 non-null  object
 50  tot_cur_bal_bin             466281 non-null  object
 51  total_rev_hi_lim_bin        466281 non-null  object
 52  revol_util_bin              466281 non-null  object
dtypes: float64(25), int64(7), object(21)
memory usage: 188.5+ MB

In [ ]:
df.head()

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,...,rev_data_missing,int_rate_bin,out_prncp_bin,loan_to_income_bin,annual_inc_bin,inq_last_6mths_bin,dti_bin,tot_cur_bal_bin,total_rev_hi_lim_bin,revol_util_bin
0,5000,5000,36,10.65,162.87,B,unknown,10,RENT,24000.0,...,1,"(9.91, 11.49]","(-0.001, 441.77]","(0.206, 0.24]","(1895.999, 34000.0]","(-0.001, 1.0]","(24.21, 28.0]","(94554.0, 129069.0]","(19700.0, 23600.0]","(78.5, 87.1]"
1,2500,2500,60,15.27,59.83,C,ryder,0,RENT,30000.0,...,1,"(14.49, 15.8]","(-0.001, 441.77]","(0.08, 0.116]","(1895.999, 34000.0]","(2.0, 33.0]","(-0.001, 7.03]","(63103.445, 94554.0]","(12500.0, 16000.0]","(-0.001, 23.2]"
2,2400,2400,36,15.96,84.33,C,unknown,10,RENT,12252.0,...,1,"(15.8, 17.57]","(-0.001, 441.77]","(0.176, 0.206]","(1895.999, 34000.0]","(1.0, 2.0]","(7.03, 10.11]","(40696.0, 63103.445]","(-15084.233, 8600.0]","(87.1, 100.0]"
3,10000,10000,36,13.49,339.31,C,air resources board,10,RENT,49200.0,...,1,"(12.49, 13.66]","(-0.001, 441.77]","(0.176, 0.206]","(49000.0, 55000.0]","(-0.001, 1.0]","(19.08, 21.46]","(63103.445, 94554.0]","(28000.0, 33466.35]","(-0.001, 23.2]"
4,3000,3000,60,12.69,67.79,B,university medical group,1,RENT,80000.0,...,1,"(12.49, 13.66]","(441.77, 3022.96]","(-0.00021100000000000003, 0.08]","(71000.0, 81000.0]","(-0.001, 1.0]","(16.87, 19.08]","(129069.0, 169125.169]","(23600.0, 28000.0]","(50.8, 57.6]"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466281 entries, 0 to 466280
Data columns (total 53 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   loan_amnt                   466281 non-null  int64
 1   funded_amnt                 466281 non-null  int64
 2   term                        466281 non-null  int64
 3   int_rate                    466281 non-null  float64
 4   installment                 466281 non-null  float64
 5   grade                       466281 non-null  object
 6   emp_title                   466281 non-null  object
 7   emp_length                  466281 non-null  int64
 8   home_ownership              466281 non-null  object
 9   annual_inc                  466281 non-null  float64
 10  verification_status         466281 non-null  object
 11  issue_d                     466281 non-null  object
 12  loan_status                 466281 non-null  object
 13  purpose                     466281 non-null  object
 14  addr_state                  466281 non-null  object
 15  dti                         466281 non-null  float64
 16  delinq_2yrs                 466281 non-null  float64
 17  earliest_cr_line            466281 non-null  object
 18  inq_last_6mths              466281 non-null  float64
 19  open_acc                    466256 non-null  float64
 20  pub_rec                     466256 non-null  float64
 21  revol_bal                   466281 non-null  int64
 22  revol_util                  466281 non-null  float64
 23  total_acc                   466256 non-null  float64
 24  initial_list_status         466281 non-null  object
 25  out_prncp                   466281 non-null  float64
 26  total_pymnt                 466281 non-null  float64
 27  total_rec_prncp             466281 non-null  float64
 28  total_rec_int               466281 non-null  float64
 29  total_rec_late_fee          466281 non-null  float64
 30  recoveries                  466281 non-null  float64
 31  collection_recovery_fee     466281 non-null  float64
 32  last_pymnt_d                465905 non-null  object
 33  last_pymnt_amnt             466281 non-null  float64
 34  last_credit_pull_d          466239 non-null  object
 35  collections_12_mths_ex_med  466140 non-null  float64
 36  acc_now_delinq              466256 non-null  float64
 37  tot_coll_amt                396009 non-null  float64
 38  tot_cur_bal                 466281 non-null  float64
 39  total_rev_hi_lim            466281 non-null  float64
 40  default                     466281 non-null  int64
 41  loan_to_income              466281 non-null  float64
 42  credit_age                  466281 non-null  float64
 43  rev_data_missing            466281 non-null  int64
 44  int_rate_bin                466281 non-null  object
 45  out_prncp_bin               466281 non-null  object
 46  loan_to_income_bin          466281 non-null  object
 47  annual_inc_bin              466281 non-null  object
 48  inq_last_6mths_bin          466281 non-null  object
 49  dti_bin                     466281 non-null  object
 50  tot_cur_bal_bin             466281 non-null  object
 51  total_rev_hi_lim_bin        466281 non-null  object
 52  revol_util_bin              466281 non-null  object
dtypes: float64(25), int64(7), object(21)
memory usage: 188.5+ MB

In [ ]:
df=df.drop(columns=['rev_data_missing','int_rate_bin','out_prncp_bin','loan_to_income_bin','annual_inc_bin','inq_last_6mths_bin','dti_bin','tot_cur_bal_bin','total_rev_hi_lim_bin','revol_util_bin'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466281 entries, 0 to 466280
Data columns (total 43 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   loan_amnt                   466281 non-null  int64
 1   funded_amnt                 466281 non-null  int64
 2   term                        466281 non-null  int64
 3   int_rate                    466281 non-null  float64
 4   installment                 466281 non-null  float64
 5   grade                       466281 non-null  object
 6   emp_title                   466281 non-null  object
 7   emp_length                  466281 non-null  int64
 8   home_ownership              466281 non-null  object
 9   annual_inc                  466281 non-null  float64
 10  verification_status         466281 non-null  object
 11  issue_d                     466281 non-null  object
 12  loan_status                 466281 non-null  object
 13  purpose                     466281 non-null  object
 14  addr_state                  466281 non-null  object
 15  dti                         466281 non-null  float64
 16  delinq_2yrs                 466281 non-null  float64
 17  earliest_cr_line            466281 non-null  object
 18  inq_last_6mths              466281 non-null  float64
 19  open_acc                    466256 non-null  float64
 20  pub_rec                     466256 non-null  float64
 21  revol_bal                   466281 non-null  int64
 22  revol_util                  466281 non-null  float64
 23  total_acc                   466256 non-null  float64
 24  initial_list_status         466281 non-null  object
 25  out_prncp                   466281 non-null  float64
 26  total_pymnt                 466281 non-null  float64
 27  total_rec_prncp             466281 non-null  float64
 28  total_rec_int               466281 non-null  float64
 29  total_rec_late_fee          466281 non-null  float64
 30  recoveries                  466281 non-null  float64
 31  collection_recovery_fee     466281 non-null  float64
 32  last_pymnt_d                465905 non-null  object
 33  last_pymnt_amnt             466281 non-null  float64
 34  last_credit_pull_d          466239 non-null  object
 35  collections_12_mths_ex_med  466140 non-null  float64
 36  acc_now_delinq              466256 non-null  float64
 37  tot_coll_amt                396009 non-null  float64
 38  tot_cur_bal                 466281 non-null  float64
 39  total_rev_hi_lim            466281 non-null  float64
 40  default                     466281 non-null  int64
 41  loan_to_income              466281 non-null  float64
 42  credit_age                  466281 non-null  float64
dtypes: float64(25), int64(6), object(12)
memory usage: 153.0+ MB

In [ ]:
 def woe_iv(df,f_bins,target): # this will take 3 inputs - dataframe , column with binned classes , target column

  grouped=df.groupby(f_bins,observed=False) # grouping my data into bins provided and to ignore the error
  eps=0.00000001
  total_good=(df[target]==0).sum() # calculating the total good loans
  total_bad=(df[target]==1).sum() #calculating the total bad loans

  newdf=pd.DataFrame()

  for name, group in grouped:  #loop runs - bin size
    good=(group[target]==0).sum() #calculating the good for the particular bin
    bad=(group[target]==1).sum() #calculating the bad for the particular bin

    dist_good=good/total_good if total_good!=0 else eps
    dist_bad=bad/total_bad if total_bad!=0 else eps

    woe=np.log((dist_good+eps)/(dist_bad+eps))
    iv=(dist_good-dist_bad)*woe

    newdf=pd.concat([
        newdf,pd.DataFrame([{
            'bin':name,
            'good':good,
            'good %':dist_good,
            'bad':bad,
            'bad %':dist_bad,
            'WoE':woe,
            'IV':iv
        }])
    ],ignore_index=True)
  total_iv=newdf['IV'].sum()
  return total_iv,newdf

In [ ]:
def iv_num_col(df, target, bins=10):
    iv_summary = []
    numerical_cols = df.select_dtypes(include=['int64','float64']).columns.drop(target)

    for col in numerical_cols:

            # bin the column
            df[f'{col}_bin'] = pd.qcut(df[col], q=bins, duplicates='drop')
            # calculate IV
            iv,_ = woe_iv(df, f'{col}_bin', target)
            iv_summary.append({'Feature': col, 'IV': round(iv,4)})

    iv_df = pd.DataFrame(iv_summary).sort_values(by='IV', ascending=False).reset_index(drop=True)
    return iv_df

In [ ]:
df.sample()

,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_title,emp_length,home_ownership,annual_inc,...,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default,loan_to_income,credit_age
171770,8050,8050,36,17.77,290.1,D,everbank,2,RENT,70100.0,...,2224.74,2016-01-01,0.0,0.0,0.0,33387.0,11700.0,0,0.114836,27.0

In [ ]:
iv_result_num=pd.DataFrame(iv_num_col(df,'default', bins=10))
iv_result_num

                       Feature      IV
0              last_pymnt_amnt  1.4657
1              total_rec_prncp  1.3701
2                    out_prncp  0.7635
3                  total_pymnt  0.6096
4                     int_rate  0.3222
5               loan_to_income  0.0624
6                   annual_inc  0.0542
7                  tot_cur_bal  0.0433
8             total_rev_hi_lim  0.0415
9               inq_last_6mths  0.0368
10                  revol_util  0.0268
11                         dti  0.0260
12               total_rec_int  0.0234
13                  credit_age  0.0147
14                tot_coll_amt  0.0067
15                   total_acc  0.0066
16                   revol_bal  0.0058
17                  emp_length  0.0048
18                 installment  0.0046
19                   loan_amnt  0.0034
20                 funded_amnt  0.0033
21                    open_acc  0.0006
22                     pub_rec  0.0006
23                        term  0.0000
24                 delinq_2yrs  0.0000
25          total_rec_late_fee  0.0000
26     collection_recovery_fee  0.0000
27                  recoveries  0.0000
28              acc_now_delinq  0.0000
29  collections_12_mths_ex_med  0.0000

In [ ]:
impt=['out_prncp',
 'int_rate',
 'grade',
 'loan_to_income',
 'annual_inc',
 'total_rev_hi_lim',
 'tot_cur_bal',
 'purpose',
 'inq_last_6mths',
 'revol_util',
 'dti',
 'verification_status',
 'home_ownership']

In [ ]:
df[impt].isna().sum()

out_prncp              0
int_rate               0
grade                  0
loan_to_income         0
annual_inc             0
total_rev_hi_lim       0
tot_cur_bal            0
purpose                0
inq_last_6mths         0
revol_util             0
dti                    0
verification_status    0
home_ownership         0
dtype: int64

In [ ]:
import pandas as pd
import statsmodels.api as sm

In [ ]:
X1 = df.drop(columns='default')

# One-hot encode all categorical variables
X1 = pd.get_dummies(X1, drop_first=True)

# Ensure all values are numeric (float64 or int64)
X1 = X1.apply(pd.to_numeric, errors='coerce')

# Drop any rows with missing values (optional, but safe for modeling)
X1 = X1.dropna()

# Align y accordingly
y = df['default'].loc[X1.index]

# Add constant and fit
X1 = sm.add_constant(X1)
logit_model = sm.Logit(y, X1)
result = logit_model.fit()
print(result.summary())